### ISSUE TITLE
TextBlock .Layout() is void - comment/intellisense wrong

### ISSUE THREAD

**Issue by Jonesie** [toptensoftware/RichTextKit#14]
The comment/intellisense on TextBlock.Layout() says it returns a paragraph when in fact, its void.

I can do a PR for this if you like.  Are you taking contribs?

**Comment by toptensoftware** [comment]
HI @Jonesie 

Thanks for reporting.  I will take PRs, but no need in this case as I can sort it easily enough and I'll need to rebuild the docs manually anyway as I use an unreleased xmldoc tool for that.  Give me a day or two as I've just rebuilt my main dev machine and still setting things up again.

Brad

**Comment by toptensoftware** [comment]
Fixed ([see here](https://www.toptensoftware.com/richtextkit/ref/Topten.RichTextKit.TextBlock.Layout))
