### ISSUE TITLE
Hang in FontFallback.GetFontRuns with latest SkiaSharp

### ISSUE THREAD

**Issue by jpobst** [toptensoftware/RichTextKit#15]
When using the latest `SkiaSharp 2.80.0` and `HarfBuzzSharp 2.6.1.5`, the following code hangs:

```
var tb = new TextBlock ();
tb.AddText ("Hello", new Style ());
Console.WriteLine (tb.MeasuredHeight);
```

This is caused by getting stuck in an infinite loop in `FontFallback.GetFontRuns ()` due to both of these lines returning 0:

```
count = typeface.GetGlyphs((IntPtr)(pch + pos), length - pos, SKEncoding.Utf32, out var glyphs);
count = RunFace.GetGlyphs((IntPtr)(pch + pos), length - pos, SKEncoding.Utf32, out var glyphs);
```

^^ This overload of `GetGlyphs` is marked as `[Obsolete]`.

It seems like something in SkiaSharp has changed and this code no longer works as expected.  I do not know enough about what is going on to determine if the RichTextKit code needs to be updated or if this is a bug in SkiaSharp.

Windows 10 - VS 2019 - netcoreapp3.1

**Comment by toptensoftware** [comment]
Hi @jpobst 

Thanks for reporting - I'll check it out.

Brad

**Comment by mattleibow** [comment]
This was a bug due to a change in the way things work. I have a fix for this: https://github.com/mono/SkiaSharp/pull/1399

I'll push out ASAP so everyone can get that sweet, sweet text going again.

**Comment by mattleibow** [comment]
@jpobst you should be able to try out the PR build: `2.80.0-pr.1399.1` on the preview feed: `https://aka.ms/skiasharp-eap/index.json`

**Comment by jpobst** [comment]
👍 Confirmed that it fixes the issue!  Thanks!

**Comment by toptensoftware** [comment]
Thanks @mattleibow and @jpobst

**Comment by mattleibow** [comment]
I have just released the NuGets into the wild: https://github.com/mono/SkiaSharp/releases/tag/v2.80.1
