### ISSUE TITLE
possible formatting bug

### ISSUE THREAD

**Issue by eman1986** [toptensoftware/RichTextKit#19]
considering the following code:

```csharp
var rs = new RichString("Test Text")
    .FontSize(14)
    .TextColor(SkColors.Blue);
```

when I do it this way the color and size are not taking.

**Comment by daltonks** [comment]
Try it like this:
```
var rs = new RichString()
    .FontSize(14)
    .TextColor(SKColors.Blue)
    .Add("Test Text");
```

When you add text, it uses the styling that came before the call to add it.

**Comment by eman1986** [comment]
When I do it that way it works, I just wanted to make sure I didn't discover a bug

**Comment by toptensoftware** [comment]
Yep, that's correct.   RichString's fluent style api uses formatting change methods to change the format of subsequently added text - not text that's already been added.
