### ISSUE TITLE
Font fallback from private font files

### ISSUE THREAD

**Issue by EYHN** [toptensoftware/RichTextKit#20]
Thank you for making this great library.

I am making a server application and need to be able to render multi-language text. Use multiple font files in different languages.

Since font files are not installed on the server, all font files must be included in the application.

Current font fallback is based on system fonts. Is there a way to set fallback from multiple private font files?

**Comment by toptensoftware** [comment]
Hi @EYHN,

Currently this isn't possible, however...

RichTextKit relies on Skia's MatchCharacter method to do the actual font matching. ([see here](https://github.com/toptensoftware/RichTextKit/blob/master/Topten.RichTextKit/FontFallback/FontFallback.cs#L83)).  It would be pretty easy to provide a swappable callback for this method so you could provide your own logic - however you'd need to implement the fallback font selection algorithm yourself.

If you're ok with that, let me know and I'll put in something so you can plug it in.

Brad

**Comment by EYHN** [comment]
Thank you for your reply.

It will be great if I can get into the fallback font selection algorithm.

**Comment by toptensoftware** [comment]
Leave it with me and I'll see what I can do.   I won't be to "get into" the font fallback algorithm - it'll be a way to replace it with your own.

**Comment by EYHN** [comment]
Any progress ?

**Comment by toptensoftware** [comment]
Sorry, not yet.  It's on my list but been busy working on the editor side branch.  I'll try to get to it asap...

**Comment by toptensoftware** [comment]
New build (133) now supports this.  See ICharacterMatcher here:

https://www.toptensoftware.com/richtextkit/ref/Topten.RichTextKit.ICharacterMatcher

For reference, the default implementation is here and just delegates to SKFontManager's equivalent method:

https://github.com/toptensoftware/RichTextKit/blob/master/Topten.RichTextKit/FontFallback/DefaultCharacterMatcher.cs
