### ISSUE TITLE
Hyphenation

### ISSUE THREAD

**Issue by sebllll** [toptensoftware/RichTextKit#21]
hi all,

i'm currently playing a bit with this api - it's really nice so far!

one thing i want to explore is hyphenation. so far, the line break algorithm works nice and also breaks lines correctly at syllables, when the strings contain soft hyphens. This is already great. 
so my idea is to prepare the strings and insert soft hyphens based on some dictionary.

a great addition to richtextkit would be to control the hyphen symbol somehow. like:
_if a line breaks at a soft hyphen, add a given hyphen character(s) at the end of this line_

and maybe hyphenation also came to your mind already and there's more opinions about this?

best,
sebl

**Comment by toptensoftware** [comment]
Hi @sebllll,

Thanks for reporting this.   Unfortunately this is probably a beyond the scope of this project given my current time constraints.  I'd be open to considering pull requests to add the feature, but right now not something I'm planning to develop myself.

The most likely thing I might be able to add is a hook into the line break algorithm that lets someone plugin ability to do hyphenation breaks.

Brad

**Comment by sebllll** [comment]
thanks for your answer!

i understand that this is not smth. that can be added quickly and am not asking for it.

if you can help me to understand your linebreaker better, i might be able to add functionality towards hyphenation to it. in case of success i'll PR it.

a concrete question is, if the linebreaker makes a difference between hyphens and soft-hyphens? at least i couldn't find a soft-hyphen here: https://github.com/toptensoftware/RichTextKit/blob/master/Topten.RichTextKit/Unicode/LineBreakClass.cs

**Comment by toptensoftware** [comment]
The line break algorithm is a port of this: https://github.com/foliojs/linebreak and uses the the LineBreakClasse.trie ([here](https://github.com/toptensoftware/RichTextKit/blob/master/Topten.RichTextKit/Resources/LineBreakClasses.trie)) which is generated by the script [here](https://github.com/toptensoftware/RichTextKit/tree/master/BuildUnicodeData) to classify characters.

Basically it's an implementation of Unicode Line Breaking Algorithm (UAX #14) - see that spec for exactly what it does.
