### ISSUE TITLE
Selection is not painted if SelectionStart is equal to the lenght of the text.

### ISSUE THREAD

**Issue by emmauss** [toptensoftware/RichTextKit#23]
The selected range  is not painted when drawing text if the SelectionStart is set to the length of the string to be drawn, and the SelectionEnd is less than the Selection start. Dragging or selecting rendered text from the end of the text does not show the blue selection background due this if one implements selection in their text control

**Comment by toptensoftware** [comment]
Thanks for reporting. Can you confirm you're using RichString (as opposed to TextBlock).

I've found an issue with RichString and will put up a fix soon.  TextBlock seems to not have the same issue.

**Comment by toptensoftware** [comment]
Should be fixed in build 133 (available now on nuget).
