### ISSUE TITLE
[Question] Style.BackgroundColor support

### ISSUE THREAD

**Issue by sady4850** [toptensoftware/RichTextKit#25]
Hi!

Do you have plans to add an ability to customise TextBlock background color ?

Thanks!

**Comment by toptensoftware** [comment]
If you mean for the textblock as a whole - probably not, but it should be pretty easy to paint that yourself before painting the text block.

If you mean for runs of text withing the text block - probably, but not sure when I'll get to it.

**Comment by sady4850** [comment]
My question was about a background for the run, understood, thank you!
