### ISSUE TITLE
Does the drawing string support Hindi language?

### ISSUE THREAD

**Issue by e-jlion** [toptensoftware/RichTextKit#36]
Hi:

 My method of using TextBlock Paint does not support Hindi problems. Is there a good solution?

Now it is drawn by the box instead of the box, and the correct one is not drawn

environment : linux environment
version : .net 5

**Comment by toptensoftware** [comment]
Thanks for reporting this.  I'll need more information in order to get this sorted.  Can you post an example program showing the issue along with details of exactly what is wrong and how you expect it to appear and I'll look into it.

**Comment by e-jlion** [comment]
> Thanks for reporting this. I'll need more information in order to get this sorted. Can you post an example program showing the issue along with details of exactly what is wrong and how you expect it to appear and I'll look into it.

Hi :
    I use the Paint method to draw Hindi, such as "परीक्षण भेजें" After drawing by Paint, the result of drawing on the Linux system is "[][][][][][][]; Help to see if you need a font library or how to solve it

**Comment by toptensoftware** [comment]
I'll need to look into this in detail to figure out what's going on, but I'm a bit time limited right now.  If I had to guess I'd say there's something going wrong with SkiaSharp's font fallback - perhaps Linux related.

As an experiment could you try calling SKFontManager.Default.MatchCharacter() with the same font and character and check that it returns a suitable type face as the fallback.  If not, then this is a problem external to RichTextKit.

Alternatively you could try setting a breakpoint in the [character matcher](https://github.com/toptensoftware/RichTextKit/blob/master/Topten.RichTextKit/FontFallback/DefaultCharacterMatcher.cs) and check what's happening.

**Comment by e-jlion** [comment]
> I'll need to look into this in detail to figure out what's going on, but I'm a bit time limited right now. If I had to guess I'd say there's something going wrong with SkiaSharp's font fallback - perhaps Linux related.
> 
> As an experiment could you try calling SKFontManager.Default.MatchCharacter() with the same font and character and check that it returns a suitable type face as the fallback. If not, then this is a problem external to RichTextKit.
> 
> Alternatively you could try setting a breakpoint in the [character matcher](https://github.com/toptensoftware/RichTextKit/blob/master/Topten.RichTextKit/FontFallback/DefaultCharacterMatcher.cs) and check what's happening.

I tried it, and now I find it doesn’t work, I’ll try again and put the obtained font library on it and try the result

**Comment by e-jlion** [comment]
> > I'll need to look into this in detail to figure out what's going on, but I'm a bit time limited right now. If I had to guess I'd say there's something going wrong with SkiaSharp's font fallback - perhaps Linux related.
> > As an experiment could you try calling SKFontManager.Default.MatchCharacter() with the same font and character and check that it returns a suitable type face as the fallback. If not, then this is a problem external to RichTextKit.
> > Alternatively you could try setting a breakpoint in the [character matcher](https://github.com/toptensoftware/RichTextKit/blob/master/Topten.RichTextKit/FontFallback/DefaultCharacterMatcher.cs) and check what's happening.
> 
> I tried it, and now I find it doesn’t work, I’ll try again and put the obtained font library on it and try the result, this  result it is ok
