### ISSUE TITLE
Publish TextEditorView reference code

### ISSUE THREAD

**Issue by neslib** [toptensoftware/RichTextKit#37]
Small feature request: would it be possible to publish the source code for TextEditorView.cs?

I know it will not compile because of the GUIKit dependency, but it would be great reference code for implementing your own text editor.

Also, since recent additions in RichTextKit, such as IME support, aren't handled in your editor videos (which are great BTW), it would be nice to have some reference code on how to use this.

**Comment by toptensoftware** [comment]
Here you go...

https://gist.github.com/toptensoftware/e3281d4e6baa505e15a730f2137208f0

**Comment by neslib** [comment]
Thank you! Much appreciated!

**Comment by toptensoftware** [comment]
TextEditorView is only sample code for how to integrate it with a gui-framework - it can't be compiled on its own.
