### ISSUE TITLE
Large PDF file sizes with text

### ISSUE THREAD

**Issue by reinux** [toptensoftware/RichTextKit#38]
I guess it's because it's vectorizing all the text (or storing the font?); files get huge pretty huge.

Is there a setting or something that might help with this?

I can provide more details if you can let me know what information would be useful.

Thanks in advance.

**Comment by toptensoftware** [comment]
Unless I'm missing something I think this is probably related to SkiaSharp more than RichTextKit.  All RichTextKit does is call the SkiaSharp functions for drawing text...
