### ISSUE TITLE
Missing LineBreakMode

### ISSUE THREAD

**Issue by Clancey** [toptensoftware/RichTextKit#4]
I can see no way to do line break mode on the Textblock.

**Comment by toptensoftware** [comment]
Do you mean just disabling line breaking?  If so [see here](https://www.toptensoftware.com/richtextkit/ref/Topten.RichTextKit.TextBlock.MaxWidth)

If you mean different types of line break methods there's currently no support for that.

**Comment by Clancey** [comment]
Correct, multiple types of LineBreak mode.

**Comment by Clancey** [comment]
For instance, typical line break modes:
 ``` cs
public enum LineBreakMode
    {
        NoWrap,
        WordWrap,
        CharacterWrap,
        HeadTruncation,
        TailTruncation,
        MiddleTruncation
    }
```

**Comment by toptensoftware** [comment]
Right.  So...

* NoWrap vs WordWrap is selected via setting MaxWidth to null/not-null.
* Character wrap mode isn't supported (although if word breaking results in nothing fitting on a line then it will switch down to character wrapping mode and put as many glyphs as possible on the line).  It should reasonably easy to add support for this.
* Truncation modes aren't supported - truncation is always at the end.  This may be easy to add if restricted to single lines of text.  I'm not sure head/middle truncation for multiple lines of text and mixed ltr/rtl even makes sense.

**Comment by Gillibald** [comment]
The issue with word wrapping is the fact that not all languages have a concept of whitespaces between words and line break opportunities aren't necessarily word boundaries. This requires adding an additional unicode algorithm as well as dictionaries for multiple languages. To get this right one has to implement a rule engine that understands the unicode spec.

**Comment by toptensoftware** [comment]
RichTextKit includes an implementation of the Unicode Line Breaking Algorithm (UAX #14).

(Note: the line breaking algorithm is different to the word boundary rules. As I understand it, word boundaries aren't necessarily the correct places to break lines)

**Comment by mgood7123** [comment]
> Right. So...
> 
>     * NoWrap vs WordWrap is selected via setting MaxWidth to null/not-null.
> 
>     * Character wrap mode isn't supported (although if word breaking results in nothing fitting on a line then it will switch down to character wrapping mode and put as many glyphs as possible on the line).  It should reasonably easy to add support for this.
> 
>     * Truncation modes aren't supported - truncation is always at the end.  This may be easy to add if restricted to single lines of text.  I'm not sure head/middle truncation for multiple lines of text and mixed ltr/rtl even makes sense.

middle truncation may make sense for things such as directory paths/names or file paths/names, where you would want to be able to see at least part of the path in a way that you can guess what directory it is located and what file it is based on the start text before the ellipsis and the end text after the ellipsis
