### ISSUE TITLE
Change TextColor of TextBlock after creation

### ISSUE THREAD

**Issue by charlenni** [toptensoftware/RichTextKit#41]
Hello,

first: thank you for this great project.

I have only one style in a TextBlock and want to change the TextColor of this text later. Is this possible? Or must I recreate the whole TextBlock?

Thank you for your help.

Best regards,
Dirk

**Comment by toptensoftware** [comment]
The text block only stores a reference to the passed in style.  So if you're careful and only use that style instance with that one text block you can change it's color property and re-draw it and the new color will be used.

Note: you can provide your own implementation of IStyle if you want.

**Comment by charlenni** [comment]
Thank you for the fast answer. Works perfect!
