### ISSUE TITLE
Different line break behavior based on how texts are added

### ISSUE THREAD

**Issue by euju-ms** [toptensoftware/RichTextKit#61]
I have the bolded text `aaaaaaaaaa` in a text block with `MaxWidth = 36` and `MaxHeight = 30`.

If I add the letters as two separate texts:
```
textBlock.AddText("aaaaa", styleBold);
textBlock.AddText("aaaaa", styleBold);
```
it results in:
![image](https://user-images.githubusercontent.com/116768779/206050622-7f48ede2-e7ec-4596-b5e3-36bd004251be.png)

On the other hand, if I add the entire text in one AddText:
```
textBlock.AddText("aaaaaaaaaa", styleBold);
```

it results in:
![image](https://user-images.githubusercontent.com/116768779/206050728-902f5b58-870f-4b36-87e5-b4090b1ef8d7.png)

I expect that I see the second image in both scenarios.

**Comment by toptensoftware** [comment]
Thanks for reporting.  Fixed.

![image](https://user-images.githubusercontent.com/179862/206059023-57fe5208-b447-4326-a9d2-77a6ed4b5bbc.png)
