### ISSUE TITLE
Is this library still active?

### ISSUE THREAD

**Issue by TopperDEL** [toptensoftware/RichTextKit#69]
I'm using it in a project of mine and love it - but it is missing some features where I hope you could help me. Are you still working on it?

I need a way to add "variables" to a text. A variable consists of a Name and a Background highlight color. It should be possible to hit test against a variable.
The TextDocument is nearly capable of doing it. It seems I am just missing a way to set a style for a part of a text (the variable) and there is no immediate way to hit test it - though I could us the caret info to check whether my click is within the scope of a variable.

Could you help me with this and maybe add that functionality? Thank you very much!

**Comment by toptensoftware** [comment]
The library is semi-active, meaning I work on it when I need something new in it. Currently it's serving my needs so nothing actively being worked on but some of the things you're asking for are things I'll be needing too, but unfortunately not right now.

**Comment by TopperDEL** [comment]
Thanks for your feedback! I'll see where I can provide a PR if necessary. The addition of the styleToUse with #70 has been very helpful already!
