### ISSUE TITLE
How to draw text along a path?

### ISSUE THREAD

**Issue by avisra** [toptensoftware/RichTextKit#92]
This library is the only thing that fixed the kerning issue that I experienced with SkiaSharp. But - how can I use this library to also draw along a curve to make the text appear in an arc?

**Comment by toptensoftware** [comment]
Drawing text along a path is not supported by this library and no plans to add it.

**Comment by charlenni** [comment]
Do you want to say, that `SKCanvas.DrawTextOnPath` doesn't work correct? If yes, what isn't working correct?

**Comment by toptensoftware** [comment]
@charlenni , sounds like font kerning isn't working correctly... which could be because it needs to be done with correct character placement using a library like harfbuzz and not skia's default draw text on path functionality.

**Comment by charlenni** [comment]
Thank you for your answer.

Skia removed this function some time ago. And, if I'm right, SkiaSharp replaced it with an own function. But if I'm read it correctly, then the TO says, that it isn't working properly.

Have to look into this again.
